name: install-node
description: Install dependencies for build and test jobs
runs:
  using: "composite"
  steps:
    - name: Use Node.js 24.x
      uses: actions/setup-node@v5
      with:
        node-version: 24.x

    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash