name: Build, Test, Publish and Deploy React App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run dev

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true

      - name: Generate JSDoc
        run: npm run jsdoc

      - name: Build React app
        run: npm run build

      - name: Copy docs into dist
        run: |
          mkdir -p dist/docs
          cp -r docs/* dist/docs/

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  publish-npm:
    needs: build_test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Check version difference
        id: version_check
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          LOCAL_VERSION=$(node -p "require('./package.json').version")
          PUBLISHED_VERSION=$(npm view $PACKAGE_NAME version || echo "0.0.0")
          
          echo "Local version: $LOCAL_VERSION"
          echo "Published version: $PUBLISHED_VERSION"
          
          if [ "$LOCAL_VERSION" = "$PUBLISHED_VERSION" ]; then
            echo "Version identical. Skipping publish."
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "New version detected."
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Build package
        if: steps.version_check.output.skip == 'false'
        run: npm run build

      - name: Publish to NPM
        if: steps.version_check.output.skip == 'false'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN}}

  docker:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v3

      - name: Build MySQL image
        run: docker build -t test-mysql -f Dockerfile.mysql .

      - name: Build FastApi image
        run: docker build -t test-api .

      - name: Run MySQL container
        run: |
          docker run -d \
          --name mysql-test \
          -e MYSQL_ROOT_PASSWORD=testpw \
          -e MYSQL_DATABASE=ynov_ci \
          -p 3306:3306 \
          test-mysql

      - name: Run API container
        run: |
          docker run -d \
           --name api-test \
            --link mysql-test:mysql \
            -e MYSQL_HOST=mysql \
            -e MYSQL_USER=root \
            -e MYSQL_PASSWORD=testpw \
            -e MYSQL_DATABASE=ynov_ci \
            -p 8000:8000 \
            test-api

      - name: Wait API
        run: sleep 10

      - name: Test API endpoint
        run: |
          curl --fail http://localhost:8080/users

  deploy:
    needs: publish-npm
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4